---
author: ""
date: ""
title: ""
output:
  html_document:
    toc: false
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(
  # echo = TRUE,
  echo = FALSE,
  # cache = TRUE,
  # include = FALSE,
  # results = "markdown",
  # results = "hide",
  fig.align = "center",
  # fig.show = "asis",
  fig.width = 10,
  fig.height = 10,
  # out.width = 6,
  # out.height = 6,
  warning = FALSE,
  message = FALSE
)

```

```{r load include = FALSE}
source(file.path("R", "00-config.R"))
# load(params$path_analysis_image)
schools <-
  params$path_schools_clean %>%
  teproj::import_path_cleanly()

# persons <-
#   params$path_persons_clean %>%
#   teproj::import_path_cleanly()

```

```{r}
add_name_first_pair_col <-
  function(data = NULL) {
    data %>% 
      mutate(name_first_pair = paste0(name_first, " & ", name_first_sibling)) %>% 
  }

get_siblings_by_at <-
  function(data = NULL,
           min = 2,
           max = Inf,
           cols_grp = NULL,
           prettify = TRUE) {
    cols_grp_chr <- cols_grp
    cols_grp <- syms(cols_grp)
    data_proc <-
      data %>%
      group_by(!!!cols_grp) %>%
      mutate(rnk_max = rank(name_last, ties.method = "max")) %>%
      ungroup()

    data_filt <-
      data_proc %>%
      filter(rnk_max >= min, rnk_max <= max)

    ret <-
      data_filt %>%
      left_join(data_filt,
                by = cols_grp_chr,
                suffix = c("", "_sibling")) %>%
      filter(name_first != name_first_sibling) %>%
      distinct(!!!syms(cols_grp), .keep_all = TRUE)
    
    if(prettify) {
      ret <-
        ret %>% 
        add_name_first_pair_col() %>% 
        select(
          name_first_pair,
          name,
          name_first,
          name_last,
          name_first_sibling,
          everything()) %>%
        arrange(name_last, name_first, school)
      
      cols_drop <-
        setdiff(c(names(data), "name_first_pair", "name_first_sibling"), names(ret))
      
      ret <-
        ret %>%
        select(-one_of(cols_drop))
    }
      ret
  }

get_siblings_pair_by_at <-
  function(data = NULL,
           min = 2,
           max = 2,
           ...) {
    get_siblings_by_at(data = data,
                       min = min,
                       max = max,
                       ...)
  }

```

```{r siblings_lax, include = FALSE, eval = FALSE}
# NOTE: Probably should remove this.
siblings_lax <-
  persons %>%
  get_siblings_by_at(cols_grp = c("name_last", "school", "city", "year"))

siblings_lax_n <-
  siblings_lax %>%
      group_by(school, name_last, name_first_pair) %>%
      summarise(n = n()) %>%
      ungroup() %>%
      distinct(school, name_last, n, .keep_all = TRUE) %>%
      rank_arrange_at("n")
siblings_lax_n
```

```{r siblings, include = FALSE}
siblings <-
  persons %>%
  get_siblings_by_at(
    cols_grp = c("name_last",
                        "school",
                        "city",
                        "year",
                        "conf",
                        "complvl",
                        "comp",
                        "complvl_num")
    )
siblings

siblings_n <-
  siblings %>%
  group_by(name_last, name_first_pair) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  distinct(name_last, n, .keep_all = TRUE) %>%
  rank_arrange_at("n")
siblings_n

html_siblings_n <-
  siblings_n %>%
  create_kable_filt_at(
    params = params,
    col_rgx = "name_last",
  )
```

```{r html_siblings_n, echo = FALSE, include = TRUE}
html_siblings_n
```

```{r siblings_prnk, include = FALSE}
siblings_prnk <-
  siblings %>%
  select(matches("^name|^prnk")) %>%
  gather(prak_sum_type, value, matches("^prnk")) %>%
  group_by(name_last, name_first_pair) %>%
  summarise(sum = sum(value)) %>%
  ungroup() %>%
  distinct(name_last, sum, .keep_all = TRUE) %>%
  rank_arrange_at("sum")
siblings_prnk

html_siblings_prnk <-
  siblings_prnk %>%
  create_kable_filt_at(
    params = params,
    col_rgx = "name_last",
  )

```

```{r html_siblings_prnk, echo = FALSE, include = TRUE}
html_siblings_prnk
```

