complvls_info:
- District
- Region
- State
complvls_scrape:
- district
- regional
- state
comps_info_list:
- Calculator Applications
- Computer Science
- Mathematics
- Number Sense
- Science
comps_scrape:
- cal
- csc
- mth
- num
- sci
confs:
- 1A
- 2A
- 3A
- 4A
- 5A
- 6A
confs_scrape:
- 1A
- 2A
- 3A
- 4A
- 5A
- 6A
default_city: unknown
default_complvl_num: 0.0e+00
dir_data: data
dir_scrape: data-raw
dir_viz: figs
export_data: yes
export_viz: yes
n_rnk_html: 10.0
path_dl_uil: data-raw/temp.html
path_functions_image: data/functions.RData
path_persons_uil: data/persons-uil.csv
path_persons_uil_scrape: data-raw/persons-uil-scrape.csv
path_schools_nces: data/schools-nces.csv
path_schools_nces_join: data/schools-nces-join.csv
path_schools_nces_raw: data-raw/EDGE_GEOCODE_PUBLICSCH_1516.xlsx
path_schools_uil: data/schools-uil.csv
path_schools_uil_scrape: data-raw/schools-uil-scrape.csv
rgx_name_filt: El.*[Hh]ab.*Ant
rgx_name_last_filt: El.*[Hh]ab
rgx_school_filt: CLEMENS
url_base_uil: https://www.hpscience.net/results/
url_suffix_uil: .php
viz_footer: |
  By: Tony ElHabr. Data source: https://www.hpscience.net/.
xpath_uil: /html/body/table
years:
- 2004
- 2005
- 2006
- 2007
- 2008
- 2009
- 2010
- 2011
- 2012
- 2013
- 2014
- 2015
- 2016
- 2017
years_scrape:
- 2004
- 2005
- 2006
- 2007
- 2008
- 2009
- 2010
- 2011
- 2012
- 2013
- 2014
- 2015
- 2016
- 2017

